# Generated by Django 3.2.4 on 2021-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('time', models.TimeField(primary_key=True, serialize=False)),
                ('data_records', models.JSONField()),
                ('data_filtered', models.JSONField()),
            ],
        ),
    ]
